theme: jekyll-theme-minimal

title: Donald Grasse
description: PhD Candidate | Political Science | Emory University

url: https://donaldgrasse.github.io

baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "donaldgrasse.github.io"

# Social Sharing
twitter: twitter.com
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
  
# Site Author
author:
  name             : "Your Sidebar Name"
  avatar           : "profile.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Location"
  employer         :
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "http://yourfullgooglescholarurl.com"
  email            :
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "academicpages"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         :
  orcid            : "http://orcid.org/yourorcidurl"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "donplyr"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
